name: Test
on: [push, pull_request]

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup PHP version with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install

      - name: Run code sniffer
        run: composer phpcs

      - name: Run tests
        run: composer test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage.clover:clover
